---

PACKAGES:
  - apt-mirror
  - apache2

MIRROR:
  path: /etc/apt/mirror.list
  update_cmd: su - apt-mirror -c apt-mirror
  repo_path:
    - { src: '/var/spool/apt-mirror/mirror/us.archive.ubuntu.com/ubuntu/', dest: '/var/www/ubuntu' }
    - { src: '/var/spool/apt-mirror/mirror/security.ubuntu.com/ubuntu/', dest: '/var/www/security' }
  client_path: /etc/apt/sources.list

APACHE:
  sites_available: /etc/apache2/sites-available
  sites_enabled: /etc/apache2/sites-enabled
  conf: apt-mirror.conf
  service: apache2
